### PR TITLE
Rename etsy to etsy2 and strip trailing spaces

### PR DESCRIPTION
**Pull request by jtatum**
The package is published on pypi as `etsy2`. This commit updates
the package so that it's available to import under the same name.

Trailing spaces are stripped from most files.

### CODE REVIEW

**Comment by jtatum** [comment]
BTW - might want to enable issues on this repo.

**Comment by jtatum** [comment]
If this branch is accepted, I have another behind it to fix tests (and a couple of bugs)

**Comment by sscheetz** [comment]
Sorry didn't expect anyone to actually see this so didn't expect to see PRs. Looks like a good change. I'm pretty to new to python so not sure what the conventions are for all this stuff. Can definitely keep contributing or probably take the repo as I switched gears and am writing my app in C#.

**Comment by sscheetz** [comment]
Sorry didn't get any notifications and didn't expect anyone to actually see this so wasn't looking. Seems like a good change. I'm pretty to new to python so not sure what the conventions are for all this stuff. Will push an update to pypi tonight and will be more responsive in the future.

**Pull request merged**
